return {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
        preset = "helix",
        spec = {
            {
                mode = { "n", "v" },
                { "<leader>c", group = "code" },
                { "gs", group = "surround" },
                { "g", group = "goto" },
                { "<leader>b", group = "buffers" },
                { "<leader>g", group = "git" },
                { "<leader>x", group = "diagnostics/quickfix", icon = { icon = "󱖫 ", color = "green" } },
                { "<leader>q", group = "persistance", icon = { icon = " ", color = "yellow" } },
                { "<leader>u", group = "utility", icon = { icon = "󰖷 " } },
                { "<leader>uc", desc = "Toggle multicursor" },
                { "<down>", desc = "Add cursor below" },
                { "<esc>", desc = "Enable/clear cursors" },
                { "<leader><down>", desc = "Skip cursor down" },
                { "<leader><up>", desc = "Skip cursor up" },
                { "<leader>N", desc = "Add cursor at previous match" },
                { "<leader>S", desc = "Skip previous match" },
                { "<leader>n", desc = "Add cursor at next match" },
                { "<leader>s", desc = "Skip next match" },
                { "<leader>x", desc = "Delete current cursor" },
                { "<left>", desc = "Select previous cursor" },
                { "<right>", desc = "Select next cursor" },
                { "<up>", desc = "Add cursor above" },
            },
        },
    },
    keys = {},
}
